sudo: false

cache: cargo

install: |
    echo -e "\033[33;1mDownloading Rust\033[0m" && \
    curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly-$TARGET && \
    export PATH=$HOME/.cargo/bin:$PATH

before_script: |
    pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
    rustc --version

script:
  - |
      travis-cargo build -- --features "$FEATURES" &&
      travis-cargo test -- --lib --features "$FEATURES" &&
      # need optimisations or else a full quickcheck takes too long
      travis-cargo test -- --release --features "$FEATURES full-quickcheck" &&
      travis-cargo bench -- --features "$FEATURES" &&
      travis-cargo doc -- --features "$FEATURES"

after_success:
    - if [ -z "$FEATURES" -a "$BITS" = "32" ]; then travis-cargo doc-upload; fi

matrix:
  include:
    - env:
      - TARGET=i686-unknown-linux-gnu
        BITS=32
        FEATURES=''
      addons:
        apt:
          packages:
          - libc6:i386
          - libstdc++6:i386
          - zlib1g-dev:i386
          - libssl-dev:i386
          - pkg-config:i386
          - gcc-multilib
          - libgmp-dev:i386
    - env:
      - TARGET=x86_64-unknown-linux-gnu
        BITS=64
        FEATURES=''
      addons:
        apt:
          packages:
          - libgmp-dev
    - env:
      - TARGET=i686-unknown-linux-gnu
        BITS=32
        FEATURES='fallbacks'
      addons:
        apt:
          packages:
          - libc6:i386
          - libstdc++6:i386
          - zlib1g-dev:i386
          - libssl-dev:i386
          - pkg-config:i386
          - gcc-multilib
          - libgmp-dev:i386
    - env:
      - TARGET=x86_64-unknown-linux-gnu
        BITS=64
        FEATURES='fallbacks'
      addons:
        apt:
          packages:
          - libgmp-dev
    - env:
      - TARGET=x86_64-unknown-linux-gnu
        BITS=64
        FEATURES='asm'
      addons:
        apt:
          packages:
          - libgmp-dev

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=unstable
